package com.ibm.oms.domain.persist;

import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(OrderMain.class)
public abstract class OrderMain_ {

	public static volatile SingularAttribute<OrderMain, String> orderType;
	public static volatile SingularAttribute<OrderMain, String> confirmerNo;
	public static volatile SingularAttribute<OrderMain, String> saleStoreCode;
	public static volatile SingularAttribute<OrderMain, Long> ifPriviledgedMember;
	public static volatile SingularAttribute<OrderMain, Long> ifBlackListMember;
	public static volatile ListAttribute<OrderMain, OrderCooperator> orderCooperators;
	public static volatile SingularAttribute<OrderMain, Integer> isSuspension;
	public static volatile ListAttribute<OrderMain, OrderPromotion> orderPromotions;
	public static volatile ListAttribute<OrderMain, OrderSub> orderSubs;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalPromo;
	public static volatile SingularAttribute<OrderMain, String> saleFranchiseeCode;
	public static volatile SingularAttribute<OrderMain, Integer> isBarter;
	public static volatile SingularAttribute<OrderMain, String> shipStoreName;
	public static volatile SingularAttribute<OrderMain, String> orderNoP;
	public static volatile SingularAttribute<OrderMain, Date> orderTime;
	public static volatile SingularAttribute<OrderMain, Long> ifShowPrice;
	public static volatile SingularAttribute<OrderMain, String> customerEmail;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalGivePoints;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalProductPrice;
	public static volatile SingularAttribute<OrderMain, Long> id;
	public static volatile ListAttribute<OrderMain, OrderPay> orderPays;
	public static volatile SingularAttribute<OrderMain, Date> finishTime;
	public static volatile SingularAttribute<OrderMain, String> orderRelatedOrigin;
	public static volatile SingularAttribute<OrderMain, String> orderNo;
	public static volatile SingularAttribute<OrderMain, String> updatedBy;
	public static volatile SingularAttribute<OrderMain, Long> ifWarnOrder;
	public static volatile SingularAttribute<OrderMain, String> receiveAreaId;
	public static volatile SingularAttribute<OrderMain, String> ip;
	public static volatile SingularAttribute<OrderMain, BigDecimal> weight;
	public static volatile SingularAttribute<OrderMain, Integer> isCommission;
	public static volatile SingularAttribute<OrderMain, Date> confirmTime;
	public static volatile SingularAttribute<OrderMain, String> finishUserNo;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalPayAmount;
	public static volatile SingularAttribute<OrderMain, String> shipStoreCode;
	public static volatile SingularAttribute<OrderMain, BigDecimal> discountTransport;
	public static volatile SingularAttribute<OrderMain, String> customerName;
	public static volatile ListAttribute<OrderMain, OrderItemVirtual> orderItemVirtuals;
	public static volatile SingularAttribute<OrderMain, String> memberNo;
	public static volatile SingularAttribute<OrderMain, String> memberCardLevel;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalPoint;
	public static volatile SingularAttribute<OrderMain, String> cancelReasonNo;
	public static volatile SingularAttribute<OrderMain, Long> idOrderP;
	public static volatile SingularAttribute<OrderMain, Date> balanceDate;
	public static volatile SingularAttribute<OrderMain, String> statusTotal;
	public static volatile SingularAttribute<OrderMain, Integer> isMerge;
	public static volatile ListAttribute<OrderMain, OrderStatusLog> orderStatusLogs;
	public static volatile SingularAttribute<OrderMain, String> clientRemark;
	public static volatile SingularAttribute<OrderMain, String> merchantNo;
	public static volatile SingularAttribute<OrderMain, BigDecimal> totalPointAmount;
	public static volatile SingularAttribute<OrderMain, BigDecimal> transportFee;
	public static volatile SingularAttribute<OrderMain, String> confirmerName;
	public static volatile ListAttribute<OrderMain, OrderRetChgItem> orderRetChgItems;
	public static volatile SingularAttribute<OrderMain, String> saleCompanyCode;
	public static volatile SingularAttribute<OrderMain, String> remark;
	public static volatile SingularAttribute<OrderMain, String> performStoreCode;
	public static volatile SingularAttribute<OrderMain, String> statusPay;
	public static volatile SingularAttribute<OrderMain, String> immigrationVersion;
	public static volatile ListAttribute<OrderMain, OrderItem> orderItems;
	public static volatile SingularAttribute<OrderMain, String> statusConfirm;
	public static volatile SingularAttribute<OrderMain, String> refundType;
	public static volatile SingularAttribute<OrderMain, String> customerPhone;
	public static volatile SingularAttribute<OrderMain, String> regionCode;
	public static volatile SingularAttribute<OrderMain, String> chgOurOrderNo;
	public static volatile SingularAttribute<OrderMain, Date> dateCreated;
	public static volatile SingularAttribute<OrderMain, Long> isDeleted;
	public static volatile ListAttribute<OrderMain, OrderInvoice> orderInvoices;
	public static volatile SingularAttribute<OrderMain, String> clientServiceRemark;
	public static volatile SingularAttribute<OrderMain, Long> needConfirm;
	public static volatile SingularAttribute<OrderMain, String> payOnArrivalPayType;
	public static volatile SingularAttribute<OrderMain, BigDecimal> salesclerkPerform;
	public static volatile SingularAttribute<OrderMain, String> sellerMessage;
	public static volatile SingularAttribute<OrderMain, String> salesclerkNo;
	public static volatile SingularAttribute<OrderMain, String> merchantType;
	public static volatile SingularAttribute<OrderMain, Long> remindSent;
	public static volatile SingularAttribute<OrderMain, Integer> isSplit;
	public static volatile SingularAttribute<OrderMain, String> orderSource;
	public static volatile SingularAttribute<OrderMain, Long> ifNeedRefund;
	public static volatile ListAttribute<OrderMain, OrderInvoicePrint> orderInvoicePrints;
	public static volatile SingularAttribute<OrderMain, Long> billType;
	public static volatile SingularAttribute<OrderMain, String> deliveryTimeFlag;
	public static volatile SingularAttribute<OrderMain, String> deliveryType;
	public static volatile SingularAttribute<OrderMain, String> batchNum;
	public static volatile SingularAttribute<OrderMain, Long> ifPayOnArrival;
	public static volatile ListAttribute<OrderMain, OrderPayMode> orderPayModes;
	public static volatile SingularAttribute<OrderMain, Date> dateUpdated;
	public static volatile SingularAttribute<OrderMain, Integer> totalProductCount;
	public static volatile ListAttribute<OrderMain, OrderItemAbn> orderItemAbns;
	public static volatile SingularAttribute<OrderMain, BigDecimal> discountTotal;
	public static volatile SingularAttribute<OrderMain, Long> needInvoice;
	public static volatile SingularAttribute<OrderMain, String> createdBy;
	public static volatile SingularAttribute<OrderMain, String> aliasOrderNo;
	public static volatile SingularAttribute<OrderMain, Integer> clientServiceRemarkFlag;
	public static volatile SingularAttribute<OrderMain, String> deliveryDateFlag;
	public static volatile SingularAttribute<OrderMain, String> orderCategory;

}

